version: '3.7'

services:

  redis:
    container_name: "thirdcircle-io-redis"
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "./data/redis:/var/lib/redis/data"

#  mongo:
#    container_name: "thirdcircle-data-mongo"
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - 27017:27017
